### ISSUE TITLE
consider adding mimalloc

### ISSUE THREAD

**Issue by emekoi** [mjansson/rpmalloc#101]
in the README mimalloc claims
> mimalloc always outperforms all other leading allocators (jemalloc, tcmalloc, Hoard, etc)

i'm interested to see how it compares to rpmalloc.

**Comment by mjansson** [comment]
Interesting, will add, and also use tje mimalloc benchmark suite to see how rpmalloc can improve

**Comment by mjansson** [comment]
Will do a benchmark pass once #102 is merged

**Comment by mjansson** [comment]
Benchmarks from develop branch look good, will prepare a new release soon and update the graphs including mimalloc

**Comment by mjansson** [comment]
Sorry, I've been very limited on spare time to put into these things... mimalloc is in the benchmark suite, I just haven't had time/energy to actually run through everything and generate new graphs.

**Comment by jvoisin** [comment]
rpmalloc is integrated in https://github.com/daanx/mimalloc-bench, you can see the results here for example: https://github.com/daanx/mimalloc-bench/runs/4301463727?check_suite_focus=true#step:5:945

**Comment by SunnyPaprika** [comment]
I don't think a mimalloc benchmark is relevant anymore.

Mimalloc has memory bloating problems now. Also the overall performance of mimalloc dropped. The mimalloc project does not seem to be active at the moment. 

We are currently switching to rpmalloc from mimalloc. Other projects are also dropping mimalloc because of those issues (e.g. https://github.com/pola-rs/polars/pull/7194)

**Comment by mjansson** [comment]
Interesting!

I've been too busy with paid work for the last few months but aim to come back and put some time in rpmalloc again the next few months - hopefully finishing the rewrite branch and see if that holds up as expected, and working through any issues in the current mainline.

**Comment by Dan-Do** [comment]
> I don't think a mimalloc benchmark is relevant anymore.
> 
> Mimalloc has memory bloating problems now. Also the overall performance of mimalloc dropped. The mimalloc project does not seem to be active at the moment.
> 
> We are currently switching to rpmalloc from mimalloc. Other projects are also dropping mimalloc because of those issues (e.g. [pola-rs/polars#7194](https://github.com/pola-rs/polars/pull/7194))

The issue you mentioned happen on Windows only, not Linux.

**Comment by SunnyPaprika** [comment]
> The issue you mentioned happen on Windows only, not Linux.

Same on linux, look at the rss.
