### ISSUE TITLE
possible bug in _memory_allocate at rpmalloc/rpmalloc.c:1322

### ISSUE THREAD

**Issue by gstvrmrlpz** [mjansson/rpmalloc#107]
A half finish lockfree stack implementation is triggering a bug in _memory_allocate.
Code + exe + core in https://pccito.ugr.es/bug.tar.xz

**Comment by mjansson** [comment]
Considering it segfaults using the standard malloc I think the problem is in your code

```
./stack 
  n   compress
  1     966209
free(): double free detected in tcache 2
stack: stack.cc:32: unsigned int work(std::atomic<bool>&, stack&) [with stack = compress::stack<int>]: Assertion `s.pop() == 0x12345678' failed.
Aborted (core dumped)
```

**Comment by gstvrmrlpz** [comment]
my code is full of bugs but I thought a call to new aka _memory_allocate should always success while there is enough free memory...

**Comment by mjansson** [comment]
No, not when you have corrupted the memory heap with bad calls (like a double free)

**Comment by mjansson** [comment]
From the readme: "All entry points assume the passed values are valid, for example passing an invalid pointer to free would most likely result in a segmentation fault. The library does not try to guard against errors."
