### ISSUE TITLE
Track usage of active span for lower memory footprint

### ISSUE THREAD

**Issue by mjansson** [mjansson/rpmalloc#111]
Add compile time option to enable tracking of usage in active span for each size class, which will enable returning a fully freed active span to thread cache and thereby reducing overall memory usage in use-cases with many size class scattered allocations (few allocs per class) in many threads.

This comes at a measurable performance impact since it hits the fast path in the allocator, so needs to be a compile time option.

**Comment by waddlesplash** [comment]
We've run into what I presume is another instance of this: running `git gc --aggressive` on a large repository (the Haiku one, around 300MB of git objects, works to trigger this), has *dramatically* higher area usage under rpmalloc vs. other allocators (notably our debug malloc, which is globally locked, but also glibc's malloc it seems so this should be debuggable on Linux.)

You can see via the [area listing](https://dev.haiku-os.org/attachment/ticket/15359/listarea.txt) that the innermost Git process has almost 200MB wasted just in areas with < 100KB used; and if you total the wastage across all areas, it's much bigger (a few GB it appears.)

**Comment by mjansson** [comment]
Thank you for the information, will look into this

**Comment by diversys** [comment]
This could also be the reason why I can't build LibreOffice on Haiku with ```make -j2``` with 2GB ever since we switched to rpmalloc. Admittedly, many things could have changed in LO source code but still.

**Comment by mmuman** [comment]
I'm also getting random errors due to failed allocations on things like `git pull`… doing an `export LD_PRELOAD=libroot_debug.so` fixes it.

**Comment by waddlesplash** [comment]
Here's another one with lots of "wasted memory": https://dev.haiku-os.org/attachment/ticket/15495/app_server_waste.txt

**Comment by mjansson** [comment]
This is now done in #133 - the notion of "active span" no longer exists and any fully freed span should be returned to thread cache
