### ISSUE TITLE
"Leak"? of 128kB heap areas

### ISSUE THREAD

**Issue by waddlesplash** [mjansson/rpmalloc#117]
Here's a file showing a lot of unused memory in heap areas on a running Haiku system: https://dev.haiku-os.org/attachment/ticket/15264/out.txt

The fields by order are: area ID, area name, reserved size, RAM size (i.e. touched pages.) Units are kB. As you can see, there are quite literally thousands (about ~5000) heap areas (rpmalloc is the only thing which names its areas this way) of size 128KB, and none are using more than 36kb, and most at 20kb. So there is 500MB of reserved memory in these that are not being used.

Are these the small size classes I guess? But then I'd expect more than 36kb to be used in at least some of them. There is also about 700MB wasted in 4MB heap areas towards the end of the file, but all those have varying usages so that is certainly a different issue.

**Comment by mjansson** [comment]
Yes, perhaps it could be solved by a special span flag indicating a super-aligned huge block and a base pointer. Will look into it asap.

**Comment by mjansson** [comment]
Does Haiku properly release pages when posix_madvise is called with POSIX_MADV_FREE or POSIX_MADV_DONTNEED?

I noticed the super alignment does not call madvise on the extra pages, perhaps that would be the fastest way to gain back the extra memory pages in this case.

However, the super alignments (larger than page size) will always waste one memory page as the span header needs to be stored at the start of the span of pages.

Using these huge alignments is unfortunately a bad practise with allocators like rpmalloc/mimalloc/tcmalloc that store header data at start of page ranges for performance reasons.

**Comment by mjp41** [comment]
@mjansson in [snmalloc](http://github.com/Microsoft/snmalloc), we have effectively two levels of "spans" [0], and store the meta-data at the start of the "super-spans" [1].  This means we can support large alignments with fewer wasted pages. There are a couple more instructions to find the meta-data, but not many.  This would be a fairly substantial change, but might support this use case.

[0] Called "slabs" in our [paper](https://github.com/microsoft/snmalloc/blob/master/snmalloc.pdf),
[1] Called "superslabs" in our [paper](https://github.com/microsoft/snmalloc/blob/master/snmalloc.pdf).

**Comment by mjansson** [comment]
rpmalloc actually has the same construct with "super spans", I could do some experiments by allocating super spans for large alignment requests and reuse the remainder in normal spans. 

It will only help if the number of super aligned requests are lower than normal allocations by a factor that makes up for the extra reservations, otherwise it will still be a waste.

**Comment by mjp41** [comment]
So my understanding of rpmalloc is the superspans are 64KiB (by default). In snmalloc, the superslabs are 16MiB with 16MiB alignment, and the slabs are 64KiB.  This means we get 255 slabs which are perfectly 64KiB aligned, and one slab that contains the meta-data for the other 255 slabs.  The first "short slab" has lost about 4KiB of space to meta-data.  With this architecture, it means a lot of alignment requests can be handled.  This is kind of the opposite of what you are describing above, but perhaps I am misunderstanding.

**Comment by mjansson** [comment]
Ah, so there in lies the problem, rpmalloc sort of assumes (like most performace-oriented allocators) that the OS does overcommit and that untouched pages does not consume system resources.

Perhaps a solution for this specific case would be to honor the MADV calls and add that to rpmalloc?

**Comment by waddlesplash** [comment]
Re-reading the specs, it looks like the process is allowed to touch MADV_FREE'd pages again and they will be allocated as zeroed memory, yes?

But it also appears there is MADV_REMOVE which should completely decommit and remove the given address range from the address space entirely. That may be what we want here; and implementing at least that on the kernel side of things should not be so hard.

**Comment by mjansson** [comment]
MADV_REMOVE might be dangerous if it introduces holes in the virtual memory space which will later be reused for unrelated spans while the original super aligned span still remains (then with another span spliced in inside it's range). Which will in turn fail when the original super span unmaps the entire range.

**Comment by waddlesplash** [comment]
Well, the `munmap` call will only unmap the memory at `ptr, size`; so just scale down `size` as you MADV_REMOVE. But that does sounds like a hack...

The solution to just map regularly-sized heap areas and break them up to get the super-aligned memory seems to make the most sense here, I think? How much work will that be to implement?

**Comment by mjansson** [comment]
Looking into this more, it would be a fair bit of work as it would require to coalesce all span headers at super span boundaries (4MiB or larger super spans). Also I'm not sure if this would negatively impact performance, so I would need to run some extensive performance tests.

All it all, it will probably be a couple of weeks before I have anything to test as my spare time is a bit limited at the moment.

**Comment by waddlesplash** [comment]
Another option would be to put the span headers at an unaligned address, i.e. a mask plus a subtraction from the allocation address. This would probably be not so hard to do, and one more SUB likely is a completely negligible performance cost. That way both regular alignments and super alignments would all benefit here.

**Comment by mjansson** [comment]
Problem with span headers out-of-alignment would be that the header would waste an entire memory page, which is quite significant in our case (4KiB for a 64KiB span)

**Comment by mjansson** [comment]
@waddlesplash - I've been giving this some more thought, and perhaps the easiest solution would be to simply not overmap spans on Haiku to avoid the issue of wasted physical pages due to threads reserving 4MiB on first alloc.

The idea behind the overmapping to reduce the number of syscalls and virtual mem mappings is based on the assumption that the system does overcommit and not commit physical pages unless actually touched.

You could try setting DEFAULT_SPAN_MAP_COUNT to 1 and test if performance suffers and what kind of memory usage you see.

**Comment by waddlesplash** [comment]
We can try that. But I also wonder, isn't this a problem on any 32-bit system? As you can see above, the OOM here isn't a system wide one, just this process exhausting its 2GB virtual address space I think, with almost half of that wasted memory. Doesn't a more general solution need to be found for 32 bit systems?

**Comment by mjansson** [comment]
A 32-bit build should probably also have a lower map count to avoid address space waste, yes (or set to 1 even).

If there are other issues I'll look into that as well. A dump from a process with ENABLE_STATISTICS set to 1 and calling rpmalloc_dump_statistics() would help a lot in trying to figure out where the memory pages are cached (and why).

**Comment by waddlesplash** [comment]
Hmm, actually I just realized #6 is still open. Perhaps that is part of the problem here?

**Comment by mjansson** [comment]
A dump would show that as an extra bunch of heaps compared to the number of threads running

**Comment by waddlesplash** [comment]
Well, considering app_server typically has dozens to even hundreds of threads running, I'd say it's very likely :)

Can't statistics dumps only be collected just before shutdown though? Not quite sure how I'd accomplish that here...

**Comment by mjansson** [comment]
Stats could be dumped anytime basically, just to get an idea of where memory is cached any why. Just hack in an fopen(logfile) and rpmalloc_dump_statistics(file*)

**Comment by mjansson** [comment]
Tracking the need for a different preallocation/caching strategy if system commits physical pages immediately on mmap call in #144
