### ISSUE TITLE
Mac compile error when using ENABLE_PRELOAD without ENABLE_OVERRIDE

### ISSUE THREAD

**Issue by repi** [mjansson/rpmalloc#119]
When one builds for Mac / Apple platform and use `ENABLE_PRELOAD` but do not use `ENABLE_OVERRIDE` config defines then one gets the following compile warning & error:

```
cargo:warning=In file included from /Users/johan/git/embark/rpmalloc-rs/rpmalloc-sys/rpmalloc/rpmalloc/rpmalloc.c:2520:
cargo:warning=/Users/johan/git/embark/rpmalloc-rs/rpmalloc-sys/rpmalloc/rpmalloc/malloc.c:305:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
cargo:warning=MAC_INTERPOSE_SINGLE(pthread_create_proxy, pthread_create);
cargo:warning=^
cargo:warning=/Users/johan/git/embark/rpmalloc-rs/rpmalloc-sys/rpmalloc/rpmalloc/malloc.c:305:22: error: a parameter list without types is only allowed in a function definition
cargo:warning=MAC_INTERPOSE_SINGLE(pthread_create_proxy, pthread_create);
cargo:warning=                     ^
```

From the following line: 

```
MAC_INTERPOSE_SINGLE(pthread_create_proxy, pthread_create);
```

Because with this config `USE_INTERPOSE` can only be enabled if one is using `ENABLE_OVERRIDE`.

Is `ENABLE_OVERRIDE` supposed to be required on Mac when using `ENABLE_PRELOAD` or should one simply disable the `pthread_create_proxy` interpose definition when `ENABLE_OVERRIDE` is not enabled?

**Comment by mjansson** [comment]
I guess technically it would be ok to preload without any std lib overrides, although practically it makes little sense since it will not replace any entry points.

I'll sort out the code to compile cleanly, and make a note about this in the documentation.

**Comment by repi** [comment]
Thanks for looking into it! We are currently using `ENABLE_PRELOAD` to get it to automatically register and initialize on thread creation, but we (or rather Rust) calls the memory allocator explicitly for allocations and frees.

**Comment by mjansson** [comment]
Ah, ok. I hope to get some quality time with my Mac tonight, will look at it then.

**Comment by mjansson** [comment]
Could you try the mjansson/mac-interpose branch and see if it solves the compilation issue?

**Comment by repi** [comment]
Works!
