### ISSUE TITLE
Warning if WIN32_LEAN_AND_MEAN is already defined

### ISSUE THREAD

**Issue by BobbyAnguelov** [mjansson/rpmalloc#122]
A warning occurs when trying to compile if the WIN32_LEAN_AND_MEAN is already defined. In my windows builds I have that macro defined globally via my build system. I have warnings as errors enabled so I can't compile.

ln116:

```c++
#if PLATFORM_WINDOWS
#  define WIN32_LEAN_AND_MEAN
```

should likely be

```c++
#if PLATFORM_WINDOWS
#  ifndef WIN32_LEAN_AND_MEAN
#    define WIN32_LEAN_AND_MEAN
#  endif
```

**Comment by mjansson** [comment]
Definitely a good idea, see #123
