### ISSUE TITLE
First class heaps

### ISSUE THREAD

**Issue by gfphoenix78** [mjansson/rpmalloc#125]
malloc/realloc/free has no context, so we can't group several objects to one block, and release them all. In some scenarios, users need a scope-based memory allocation, which has several advantages:
* No need to call `free()`, resetting a heap object does freeing all objects allocated by the heap.
* No need to call `free()` explicitly, means no memory leak if we finally reset/delete the heap object
* Scope-based management
* Group a set of objects by lifetime, and free all of them at one by call *heap_free()*.

**Comment by mjansson** [comment]
Adding support for first-class heap control has been on my mind for a while, I will have a look at adding that.

**Comment by gfphoenix78** [comment]
Glad to hear that!

**Comment by mjansson** [comment]
Initial implementation done in mjansson/first-class-heaps branch

**Comment by gfphoenix78** [comment]
Can we allocate the struct of heap A from heap B or using an existing struct object? So, we could simply free or transfer the pages allocated by the heap A, if we need to reset/free all object from heap A. Like:
```
// Top heap
heap_t *h_B = rpmalloc_allocate_heap(NULL, options);
...
heap_t *h_A = rpmalloc_allocate_heap(h_B, options);
char *data1 = rpmalloc_alloc(h_A, 16);
struct foo_bar *obj;
obj = rpmalloc_alloc(h_A, sizeof(*obj));
...
rpmalloc_reset_heap(h_A); // release all memory objects allocated by h_A, not h_A itself.
rpmalloc_reset_heap(h_B); // this call will release the heap A
// rpmalloc_release_heap(h_B); // this will all heap children and memory objects allocate by them, and then release the heap itself.
```
Actually the relation of heap B and A above is parent-child, resetting parent heap will release all children heaps/memory objects. If you don't want to make it complicated, it is easily done by the users.

**Comment by mjansson** [comment]
No, the heaps will not keep track of what is allocated, just raw memory blocks. So you will need to do the release of the heap objects manually.

**Comment by mjansson** [comment]
I'm wrapping up some fixes and finalizations of this, expect it to be done in a week.

**Comment by gfphoenix78** [comment]
> No, the heaps will not keep track of what is allocated, just raw memory blocks. So you will need to do the release of the heap objects manually.

No need to keep track of what is allocated. To release all memory objects all at once, simply releasing the whole memory blocks could be enough.

**Comment by mjansson** [comment]
Merged to develop branch
