### ISSUE TITLE
Exceptions rpfree

### ISSUE THREAD

**Issue by Portiella** [mjansson/rpmalloc#127]
Hi,

How can I handle exceptions in rpfree?
sometimes I have pointers made by malloc and I wish I could release those points with rpfree.

Thx

**Comment by mjansson** [comment]
rpmalloc is not designed to be resilient to errors, you must never pass a bad pointer to rpfree, or any pointer to a memory block allocated outside of rpmalloc

**Comment by Portiella** [comment]
I know, but I have that casuistry.
Any ideas that can help me?

**Comment by mjansson** [comment]
Do you use the malloc overrides, or call rp* functions directly?

**Comment by Portiella** [comment]
call rpfree

**Comment by mjansson** [comment]
Then only pass pointers to rpfree that you allocated using the rpmalloc series of functions, or am I missing something?

**Comment by Portiella** [comment]
First sorry for my English.
I want to use your memory manager because according to my tests it is much faster than new / delete from CRT.
In my case all the new assignments that my code makes use rpmalloc but in many cases I have to delete from a third-party pointer that can be rpmalloc or CRT.
I had always thought of doing rpfree but if the pointer is a new operator CRT, an exception is thrown, and I wish I could capture it.
I have no way of knowing if doing rpfree is a pointer created by CRT or by rpmalloc.

**Comment by mjansson** [comment]
Then I understand. Unfortunately, for performance reasons, there is no good way to know if a pointer is allocated by rpmalloc or not. The library expects the user to pass valid pointers to rpfree.

I guess the library could keep track of memory pages it owns and check if the pointer is within those, but that would come at a performance cost. I can add a feature request for that for future implementation.

**Comment by dcou** [comment]
FWIW, Intel TBB allocator supports this using a magic number for each of its span I think, might be a good solution without incurring any performance penalty...

**Comment by mjansson** [comment]
Problem is that unless you know it is a pointer to a block allocated by rpmalloc, it is generally not safe to access the span header to check the magic since that is usually located in another memory page -> might segfault if it is a pointer from some other allocator implementation.

**Comment by Portiella** [comment]
At the moment I am solving the issue by marking the buffer with some magic numbers and it works for me.
The performance has increased significantly.
If the library is improved in the future I will change the code to improve it.

Thank you very much for everything
