### ISSUE TITLE
Add a realloc()-like function that fails if it can't grow in place

### ISSUE THREAD

**Issue by DanielGibson** [mjansson/rpmalloc#128]
Hi, regarding https://twitter.com/maniccoder/status/1203589175120990209:

Especially when using an allocator with C++, it's useful to have a realloc()-like function that does **not** implicitly allocate+memcpy()+free memory like standard realloc() does if it can't grow in place.
The most common usecase is probably implementing a dynamic array (like std::vector): If you need to grow the internal buffer, memcpy()-ing the existing elements to a new location is not an option, you need to call move- (or copy-) constructors and the destructors of the old elements.
However, if the buffer can be grown in place that's of course desirable because it spares all the overhead of moving/copying elements.

jemalloc has something like that: `size_t xallocx(void *ptr, size_t size, size_t extra, int flags)`.
It returns the number of bytes actually allocated, which seems to be a number `< size` in the failure-case (which I find a bit awkward, it could just return 0?).
`extra` allows to specify that you'd take even more memory if possible, but getting just `size` bytes would be ok - this is also kinda handy, so you can use `size` for how much your array buffer really needs to grow for the current operation, and set `extra` to `size*0.5` to grow by a factor of about 1.5 if possible (which is supposed to be optimal, as far as I know).

I suggest adding a similar function (though I personally could live without the `extra` argument if it causes too much work).
**Or** introduce a new flag (like `RPMALLOC_GROW_OR_FAIL`) for `rpaligned_realloc()` and make it return NULL if growing in place was not possible.

Cheers,
Daniel

**Comment by mjansson** [comment]
Implementation available in mjansson/reallow-grow-or-fail branch

**Comment by DanielGibson** [comment]
This looks great, thanks a lot!
(Sorry, haven't gotten around to testing it yet)
