### ISSUE TITLE
Preconfigured page size and enabled huge pages does not call AdjustTokenPrivileges on Windows

### ISSUE THREAD

**Issue by mjansson** [mjansson/rpmalloc#138]
Enabling RPMALLOC_CONFIGURABLE and settings both page size and enable huge pages in the config struct results in AdjustTokenPrivileges not being called, causing VirtualAlloc to fail.

AdjustTokenPrivileges should be called whenever huge pages are enabled and available.

**Comment by mjansson** [comment]
@aganea Could you try this fix in #148 to see if it works for you?

**Comment by aganea** [comment]
Sure will do over the weekend or next week. I've hooked your benchmark API into LLVM instead of using rpmalloc directly, so I can test the other allocators as well. I'll post the results next week.

**Comment by aganea** [comment]
Tested & works, thanks!
