### ISSUE TITLE
Fill malloc data with zeros after freeing

### ISSUE THREAD

**Issue by iamironz** [mjansson/rpmalloc#141]
I want to create small sanitizer for my sample project and would like to know the better way how to fill `malloc(size_t)` with zeroes after calling `free()`. Can you plase suggest a better way inside allocator codebase?

Thank you.

**Comment by mjansson** [comment]
You cannot, as the allocator uses the freed block to create a fast free list of pointers in the thread cache. Modifying the block after free() will result in Bad Things<tm> happening in the allocator.

**Comment by iamironz** [comment]
This point is valid but my real case little bit different than I've described my above because NDA. Okay, just imagine: I need to call zero fill `memset`  inside `free` allocator code base. How can I get size parameter of malloc(size_t) inside implementation of `free()` method?

**Comment by mjansson** [comment]
Look at _memory_deallocate() function, it masks the pointer to get the span header, inside there is the meta data to find the block size (also see _memory_usable_size).

Warning still applies though, it is not safe to touch the memory block after the _memory_deallocate function has executed since the memory block is used by the allocator.

**Comment by iamironz** [comment]
Do you mean this part of code: 

```c
span_t* span = (span_t*)((uintptr_t)p & _memory_span_mask);
```

and this: 

```c
uint32_t blk_size = span->block_size;
```

is the allocated memory block with aligned offset which contains my malloc'ed data?

**Comment by mjansson** [comment]
Yes, if it is a small/medium block. For large or huge blocks the number of spans or memory pages are stored in the span count variable, as you can see in _memory_usable_size

**Comment by iamironz** [comment]
Seems like it works, thank you!
