### ISSUE TITLE
Does it implement Wait-free that has no CAS operation?

### ISSUE THREAD

**Issue by dingsp** [mjansson/rpmalloc#154]

**Comment by dingsp** [comment]
Is it possible to use ring-buffer data struct which can offer publisher-consumer queue with low concurrency delay to implement CAS-free allocator?

**Comment by mjansson** [comment]
I'm not sure how this relates to rpmalloc?

**Comment by mjp41** [comment]
@dingsp As far as I understand `rpmalloc` is using this as a Treiber stack with `push one` and `pop all` for the `span_free_deferred` structure, hence does not require ABA protection.  But would only provide lock-free progress.

I don't think a ring-buffer would be good as the bounded nature means you may run out of capacity, which would be considerably worse than a CAS loop. 

The design of [snmalloc](http//github.com/Microsoft/snmalloc/) uses a wait-free non-linearisable [message queue](https://github.com/microsoft/snmalloc/blob/master/src/ds/mpscq.h). I believe the `span_free_deferred` structure could potentially reuse this data structure, but it is unclear if it would provide any benefit.

@mjansson out of intereest on 
https://github.com/mjansson/rpmalloc/blob/886245b464e70f3339deaa8dfbbe1d9e383b3ad3/rpmalloc/rpmalloc.c#L1010-L1011

You could use an interlocked exchange and not require the loop. This might perform slightly better in a contended scenario.

**Comment by mjansson** [comment]
Regarding the exchange, that is a good point and I will look into fixing this asap

**Comment by dingsp** [comment]
> @dingsp As far as I understand `rpmalloc` is using this as a Treiber stack with `push one` and `pop all` for the `span_free_deferred` structure, hence does not require ABA protection. But would only provide lock-free progress.
> 
> I don't think a ring-buffer would be good as the bounded nature means you may run out of capacity, which would be considerably worse than a CAS loop.
> 
> The design of [snmalloc](http//github.com/Microsoft/snmalloc/) uses a wait-free non-linearisable [message queue](https://github.com/microsoft/snmalloc/blob/master/src/ds/mpscq.h). I believe the `span_free_deferred` structure could potentially reuse this data structure, but it is unclear if it would provide any benefit.
> 
> @mjansson out of intereest on
> https://github.com/mjansson/rpmalloc/blob/886245b464e70f3339deaa8dfbbe1d9e383b3ad3/rpmalloc/rpmalloc.c#L1010-L1011
> 
> You could use an interlocked exchange and not require the loop. This might perform slightly better in a contended scenario.

I write a demo use bounded ring-buffer and use a garbage collector to cache block unbounded, the garbage collector will give its block into ring-buffer, The demo is based on fc_malloc, it is CAS-free
