### ISSUE TITLE
Bug: Infinite Infinite Loop in test/main.c

### ISSUE THREAD

**Issue by kphillisjr** [mjansson/rpmalloc#161]
There is a race condition/failure where when 16 threads are ran that this section of code will result in a infinite loop at thread_yield.
https://github.com/mjansson/rpmalloc/blob/886245b464e70f3339deaa8dfbbe1d9e383b3ad3/test/main.c#L644-L653

The source of the infinite loop is that there is no guarantee that all threads will pass the three error checks shown on these lines. If a single thread fails any one of these tests, and the rest of the threads pass, the end result is one of the threads will get stuck in an infinite loop.

https://github.com/mjansson/rpmalloc/blob/886245b464e70f3339deaa8dfbbe1d9e383b3ad3/test/main.c#L601-L621

**Comment by mjansson** [comment]
Nice catch, I've added an early-out for all threads if one fails to avoid getting stuck on finalization phase

Included in the x86 heap sharing fix branch, mjansson/heap-page-sharing
