### ISSUE TITLE
Disabling ENABLE_THREAD_CACHE / ENABLE_GLOBAL_CACHE doesn't compile

### ISSUE THREAD

**Issue by lundmark** [mjansson/rpmalloc#164]
Trying to set these defines to 0 doesn't compile:

`rpmalloc.c(1488): error C2039: 'span_cache_deferred': is not a member of 'heap_t'`
`rpmalloc.c(423): note: see declaration of 'heap_t'`
`rpmalloc.c(1488): error C2198: 'atomic_load_ptr': too few arguments for call`
`rpmalloc.c(1490): error C2039: 'span_cache_deferred': is not a member of 'heap_t'`
`rpmalloc.c(423): note: see declaration of 'heap_t'`
`rpmalloc.c(1490): warning C4047: 'function': 'atomicptr_t *' differs in levels of indirection from 'span_t *'`
`rpmalloc.c(1490): warning C4022: 'atomic_cas_ptr': pointer mismatch for actual parameter 1`
`rpmalloc.c(1490): error C2198: 'atomic_cas_ptr': too few arguments for call`
`rpmalloc.c(2520): error C2039: 'span_cache': is not a member of 'heap_t'`
`rpmalloc.c(423): note: see declaration of 'heap_t'`
`rpmalloc.c(2516): warning C4473: 'fprintf' : not enough arguments passed for format string`
`rpmalloc.c(2516): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings`
`rpmalloc.c(2516): note: placeholders and their parameters expect 12 variadic arguments, but 11 were provided`
`rpmalloc.c(2516): note: the missing variadic argument 12 is required by format string '%10u'`

The reason why we want to do this is because we're seeing very large overheads for each thread cache. Sometimes around 100 mbyte per thread. Unfortunately this amount of overhead is not acceptable for us and we want to decrease this overhead to the cost of increased performance cost. 

Any other suggestions as to how to accomplish this would be greatly appreciated. 

Thanks!

**Comment by mjansson** [comment]
I will take a look at this, meanwhile you can try enabling the adaptive thread cache with ENABLE_ADAPTIVE_THREAD_CACHE

You can also try tuning the multiplier of the thread cache size with THREAD_CACHE_MULTIPLIER

**Comment by mjansson** [comment]
Should now be possible to compile with disabled caches

**Comment by lundmark** [comment]
Hi, that's insanely fast. Thank you so much!
