### ISSUE TITLE
Free and used bytes for a heap

### ISSUE THREAD

**Issue by sebastiangonsal** [mjansson/rpmalloc#167]
How do i get total used and free size for a first class heap?

**Comment by sebastiangonsal** [comment]
Is this the right way to do this: Go over the `full_span` list in the heap and use `block_count` for total number of blocks, `used_count` for used blocks and `blocks_size` to calcualte number of bytes?

**Comment by mjansson** [comment]
Look at the `rpmalloc_thread_statistics` function to get an idea on how to iterate and inspect the partial spans. 

The `full_span` list has spans that are fully used, so all blocks in those spans are in use (i.e allocated size is `block_count * block_size` for the corresponding size class, or simply the entire span size if you want to include the overhead). Make sure to check for SIZE_CLASS_LARGE and SIZE_CLASS_HUGE as well.
