### ISSUE TITLE
Does it support windows driver call?

### ISSUE THREAD

**Issue by Waterman178** [mjansson/rpmalloc#170]
As the title

**Comment by mjansson** [comment]
Not sure exactly what you mean, could you elaborate?

**Comment by Waterman178** [comment]
> 不确定您的意思是什么，可以详细说明吗？

I want to use malloc function in the kernel .

**Comment by mjansson** [comment]
No, this is intended as a user space malloc replacement, it is not intended for kernel space allocation.
