### ISSUE TITLE
Errors when compiling with mingw-w64

### ISSUE THREAD

**Issue by edubart** [mjansson/rpmalloc#179]
First there is this error:
```
rpmalloc/rpmalloc.c:123:12: fatal error: Windows.h: No such file or directory
  123 | #  include <Windows.h>
```

Changing to `<windows.h>` fix that, but then:

```
rpmalloc/rpmalloc.c: In function ‘rpmalloc_initialize_config’:
rpmalloc/rpmalloc.c:2506:15: warning: implicit declaration of function ‘FlsAlloc’; did you mean ‘TlsAlloc’? [-Wimplicit-function-declaration]
 2506 |     fls_key = FlsAlloc(&_rpmalloc_thread_destructor);
      |               ^~~~~~~~
      |               TlsAlloc
rpmalloc/rpmalloc.c: In function ‘rpmalloc_finalize’:
rpmalloc/rpmalloc.c:2569:2: warning: implicit declaration of function ‘FlsFree’; did you mean ‘TlsFree’? [-Wimplicit-function-declaration]
 2569 |  FlsFree(fls_key);
      |  ^~~~~~~
      |  TlsFree
rpmalloc/rpmalloc.c: In function ‘rpmalloc_thread_initialize’:
rpmalloc/rpmalloc.c:2591:4: warning: implicit declaration of function ‘FlsSetValue’; did you mean ‘TlsSetValue’? [-Wimplicit-function-declaration]
 2591 |    FlsSetValue(fls_key, heap);
      |    ^~~~~~~~~~~
      |    TlsSetValue
rpmalloc/rpmalloc.c: In function ‘rpmalloc_thread_finalize’:
rpmalloc/rpmalloc.c:2607:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
 2607 | 
```

**Comment by mjansson** [comment]
Been a while since I tried mingw, will have a look.

**Comment by mjansson** [comment]
The fiber local storage APIs are used to get an automatic callback when the thread dies on Windows platform. Unfortunately the thread local storage API does not have a similar feature as far as I know.

**Comment by JohannesLorenz** [comment]
We have the same issue when building LMMS. Any plans when this will get fixed?

**Comment by mjansson** [comment]
I guess it could be worked around by doing a DLL lookup for the symbols at runtime at the expense of code readability.

Or if it is just the headers that are lacking (and the import lib has it) you could just declare it yourself.

Try adding

`extern DWORD FlsAlloc(PFLS_CALLBACK_FUNCTION lpCallback);
extern BOOL FlsFree(DWORD dwFlsIndex);
extern BOOL FlsSetValue(DWORD dwFlsIndex, PVOID lpFlsData);`

just below the windows.h include and see if it links or if you get undefined symbol errors.

**Comment by JohannesLorenz** [comment]
@mjansson Linker errors, indeed:

```
[100%] Linking CXX executable ../lmms.exe
3rdparty/rpmalloc/librpmalloc.a(rpmalloc.c.obj): In function `rpmalloc_initialize_config':
/root/project/src/3rdparty/rpmalloc/rpmalloc/rpmalloc/rpmalloc.c:2646: undefined reference to `FlsAlloc'
3rdparty/rpmalloc/librpmalloc.a(rpmalloc.c.obj): In function `rpmalloc_thread_initialize':
/root/project/src/3rdparty/rpmalloc/rpmalloc/rpmalloc/rpmalloc.c:2739: undefined reference to `FlsSetValue'
/root/project/src/3rdparty/rpmalloc/rpmalloc/rpmalloc/rpmalloc.c:2739: undefined reference to `FlsSetValue'
/root/project/src/3rdparty/rpmalloc/rpmalloc/rpmalloc/rpmalloc.c:2739: undefined reference to `FlsSetValue'
/root/project/src/3rdparty/rpmalloc/rpmalloc/rpmalloc/rpmalloc.c:2739: undefined reference to `FlsSetValue'
3rdparty/rpmalloc/librpmalloc.a(rpmalloc.c.obj): In function `rpmalloc_thread_finalize':
/root/project/src/3rdparty/rpmalloc/rpmalloc/rpmalloc/rpmalloc.c:2753: undefined reference to `FlsSetValue'
3rdparty/rpmalloc/librpmalloc.a(rpmalloc.c.obj): In function `rpmalloc_finalize':
/root/project/src/3rdparty/rpmalloc/rpmalloc/rpmalloc/rpmalloc.c:2717: undefined reference to `FlsFree'
collect2: error: ld returned 1 exit status
src/CMakeFiles/lmms.dir/build.make:571: recipe for target 'lmms.exe' failed
```

How to fix this?

**Comment by mjansson** [comment]
Then the symbols has to be found in runtime with LoadLibrary and GetProcAddress from kernel32.dll

**Comment by JohannesLorenz** [comment]
@mjansson In LMMS, we fixed this now [in our CMakeLists](https://github.com/LMMS/lmms/pull/5696/commits/511f2e4d6e5943ab472fc5839b0a543413837d00#diff-4eb06a7c411d1f122d0a59f53d9389d8). So it probably all works on your development branch if you add `-D_WIN32_WINNT=0x600` to your build scripts.

Thanks to @DomClark who submitted this patch to LMMS.

**Comment by mjansson** [comment]
Then it must be something in the mingw headers that wrongly define that to the lowest possible value or something, the (correct) default behaviour should be to use the latest available version.

In the normal Microsoft windows header it gets defined to 0x0A00 (i.e Windows10 SDK version) by default.
