### ISSUE TITLE
Cppcheck assorted issues with rpmalloc

### ISSUE THREAD

**Issue by RanierV** [mjansson/rpmalloc#181]
Hi,
Can you consider take a look?

1. Variable aligned_size reassigned (malloc.c)
extern inline void* RPMALLOC_CDECL
pvalloc(size_t size) {
	get_thread_heap();
	size_t aligned_size = size;
	const size_t page_size = _rpmalloc_page_size();
	if (aligned_size % page_size)
		aligned_size = (1 + (aligned_size / page_size)) * page_size;
#if ENABLE_VALIDATE_ARGS
	if (aligned_size < size) {
		errno = EINVAL;
		return 0;
	}
#endif
	return valloc(size);
}

could be:

extern inline void* RPMALLOC_CDECL
pvalloc(size_t size) {
	get_thread_heap();
#if ENABLE_VALIDATE_ARGS
	size_t aligned_size = size;
	const size_t page_size = _rpmalloc_page_size();
	if (aligned_size % page_size)
		aligned_size = (1 + (aligned_size / page_size)) * page_size;
	if (aligned_size < size) {
		errno = EINVAL;
		return 0;
	}
#endif
	return valloc(size);
}

2. Duplicate if else blocks (rpmalloc.c)
#if ENABLE_THREAD_CACHE
		if (heap->finalize) {
			for (size_t ispan = 0; ispan < span_cache->count; ++ispan)
				_rpmalloc_span_unmap(span_cache->span[ispan]);
		} else {
#if ENABLE_GLOBAL_CACHE
			_rpmalloc_stat_add64(&heap->thread_to_global, span_cache->count * (iclass + 1) * _memory_span_size);
			_rpmalloc_stat_add(&heap->span_use[iclass].spans_to_global, span_cache->count);
			_rpmalloc_global_cache_insert_spans(span_cache->span, iclass + 1, span_cache->count);
#else
			for (size_t ispan = 0; ispan < span_cache->count; ++ispan)
				_rpmalloc_span_unmap(span_cache->span[ispan]);
#endif

if ENABLE_THREAD_CACHE is defined and ENABLE_GLOBAL_CACHE is not defined both blocks are equals?
			for (size_t ispan = 0; ispan < span_cache->count; ++ispan)
				_rpmalloc_span_unmap(span_cache->span[ispan]);

**Comment by mjansson** [comment]
Actually I think the current pvalloc does not do everything it should, it might return less than a page in some cases. Fixed that and used alignment code inside rpmalloc instead.

Also rearranged heap release code blocks to avoid identical if-else when global cache disabled.

Check pull request #183 and see if it solves your cppcheck issues

**Comment by RanierV** [comment]
Em ter., 25 de ago. de 2020 às 16:20, Mattias Jansson <
notifications@github.com> escreveu:

> Actually I think the current pvalloc does not do everything it should, it
> might return less than a page in some cases. Fixed that and used alignment
> code inside rpmalloc instead.
>
> Also rearranged heap release code blocks to avoid identical if-else when
> global cache disabled.
>
Thanks.

Ranier Vilela
