### ISSUE TITLE
Is there an api to walk the allocated heap or any other tooling for leak detection?

### ISSUE THREAD

**Issue by santagada** [mjansson/rpmalloc#215]
I've tried searching a bit in the source and Readme but couldn't find any information. Is there any tools or plans to have tools to help with leaked memory? For example in dlmalloc you can walk all memory allocated in a mspace, it is very useful on debug to be able to tag all memory allocations and then walk them to find leaked memory.

**Comment by mjansson** [comment]
No, there is not unfortunately, for two reasons:

1) rpmalloc's primary purpose is performance, and you do not want tracking and tracing in final production builds if your goal is highest possible performance.

2) A secondary goal is to keep the code as small as possible to avoid maintenance and integration pains.

Thus I believe a tracker (and also overwrite guards) is better implemented outside the core allocator as a secondary layer, as I've done in my foundation library (https://github.com/mjansson/foundation_lib/blob/ab5fdf85fff1eb934a4004b924aebe5122c6e058/foundation/memory.c#L518)
