### ISSUE TITLE
Modern CMake build system

### ISSUE THREAD

**Issue by friendlyanon** [mjansson/rpmalloc#224]
I think this is an impressive library, however its build tooling usage makes it difficult to use.

I would like to introduce **modern** CMake to the project and I have a sample [here](https://github.com/friendlyanon/cxx-static-shared-example) which shows what exactly would that look like. I see #159 however that PR is pretty much unusable and doesn't provide everything specified by the project's README.

* Using CMake would allow some of the platform dependant macro stuff in `rpmalloc.h` to be moved into the build system.
* Using CMake would allow trivial packaging of the library to be distributed by distros or general reuse.

Before I start working on a PR, I would like to know if you prefer to keep the old build files to provide a transition period for users of this library? If yes, then my PR won't touch those files.

**Comment by mjansson** [comment]
I've decided not to include secondary build systems into the repo, the basic idea of the source code is that should be easy to drop into any codebase instead of building separately. The docs will be updated to reflect this. Thank you for the PR though!

**Comment by friendlyanon** [comment]
The thing about omitting a build system from a library is that now each user has to write and maintain their own code that makes rpmalloc part of their build tree. It can't be guaranteed that they will get things right and they might end up with issues that a library provided build system would most definitely spare them of. This also extends to package maintainers, which is probably one of the reasons behind this library not being packaged on any platform at the moment. Forcing package maintainers to write their own build files for distribution WILL inevitably introduce issues downstream that a proper build system would have avoided and package maintainers don't usually maintain a single package, so there will inevitably be issues.

This library provides impressive performance compared to the competition according to the numbers in the README, so there is value in making the library as easy and seamless to consume and package as possible. Supporting no build system is not exactly that.

**Comment by mjansson** [comment]
Yes, but the point is that you should not really build it separately, the build system included is just to use while developing the actual library.

The idea is that you simply drop the source code into your own codebase, which is why it's written to be as self-contained as possible without relying on outside configuration directives (to the extent that is possible).

**Comment by friendlyanon** [comment]
I am trying to understand the rationale. Why is it better to "just" drop the source into codebases as opposed to provide a trivially consumable library? That doesn't make anything simple as pointed out by the above reply, quite the opposite in fact.
