### ISSUE TITLE
GitHub Actions CI

### ISSUE THREAD

**Issue by friendlyanon** [mjansson/rpmalloc#229]
This is for tracking https://github.com/mjansson/rpmalloc/issues/224#issue-806012592

After the above PR is merged, I'll work on a PR to add CI.

**Comment by mjansson** [comment]
I've decided not to include secondary build systems into the repo, the basic idea of the source code is that should be easy to drop into any codebase instead of building separately. The docs will be updated to reflect this. Thank you for the PR though!

**Comment by friendlyanon** [comment]
Regardless of the issue text, introducing a CI worklow for the library would still be of great value.
