### ISSUE TITLE
Error while running configure.py.

### ISSUE THREAD

**Issue by Sidharth-Saha** [mjansson/rpmalloc#243]
I am getting an error when I attempt to run configure.py.
Traceback (most recent call last):
  File "configure.py", line 12, in <module>
    generator = generator.Generator(project = 'rpmalloc', variables = [('bundleidentifier', 'com.rampantpixels.rpmalloc.$(binname)')])
  File "build\ninja\generator.py", line 104, in __init__
    self.toolchain.initialize(project, archs, configs, includepaths, dependlibs, libpaths, variables, self.subninja)
  File "build\ninja\msvc.py", line 75, in initialize
    self.build_toolchain()
  File "build\ninja\msvc.py", line 131, in build_toolchain
    installed_versions = vslocate.get_vs_installations()
  File "build\ninja\vslocate.py", line 92, in get_vs_installations
    dll = ctypes.WinDLL(dll_path)
  File "C:\Users\ssaha\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by mjansson** [comment]
The Visual Studio locator script did not handle errors gracefully. This has now been fixed.

If you don't have a Visual Studio version installed, use the --toolchain argument to configure script with either clang or gcc, depending on what you want to use.

**Comment by Sidharth-Saha** [comment]
I do have a Visual Studio version installed but am still getting this error.

**Comment by Sidharth-Saha** [comment]
I have a Visual Studio version installed and am still getting this error.

**Comment by mjansson** [comment]
Are you on the develop branch?

**Comment by Sidharth-Saha** [comment]
Yes.

**Comment by mjansson** [comment]
Are you running 32-bit Windows, or 64-bit?

**Comment by Sidharth-Saha** [comment]
64 bit

**Comment by mjansson** [comment]
The build setup scripts are hardcoded to load the 64-bit Visual Studio Installer DLL, but it seems you are running a 32-bit version of Python? Your path being

"C:\Users\ssaha\AppData\Local\Programs\Python\Python38**-32**\..."

Which is, I think, why it fails to load the DLL and cannot locate the Visual Studio paths.

**Comment by Sidharth-Saha** [comment]
Ok I installed a 64 bit version of python and was bale to complete the build. Thank you.

**Comment by mjansson** [comment]
Nice. Note that you don't really need the build system in this repo, the rpmalloc source should be pretty much drop-in into your own projects without too much hassle, should compile cleanly with most Visual Studio, gcc and clang versions.
