### ISSUE TITLE
possible infinite loop in _rpmalloc_span_finalize from rpmalloc.c

### ISSUE THREAD

**Issue by gstvrmrlpz** [mjansson/rpmalloc#247]
I reach a infinite loop involving "while (block)..." in this function.
My code is lockfree stack for class...
Sample code can is in https://pccito.ugr.es/bug
As it shows randomly I trigger it with
    while true, do ./stack; done
After bug is detected I attach gdb to the process but I can't discover the reason...

**Comment by mjansson** [comment]
Probably your code does a double free or similar error, which corrupts the heap

**Comment by gstvrmrlpz** [comment]
bug found in my code... rpmalloc seems to be ok!!! :)
