### ISSUE TITLE
Observe extremely high memory footprint in rpmalloc-benchmark

### ISSUE THREAD

**Issue by FujiZ** [mjansson/rpmalloc#251]
Recently I've being trying to reproduce the result in rpmalloc-benchmark, but I observed that rpmalloc consumed much more memory than other allocators (e.g. tcmalloc, jemalloc) in some cases. For example, I ran the benchmark with the same parameters mentioned in https://github.com/mjansson/rpmalloc-benchmark/blob/master/BENCHMARKS.md#random-size-in-512-16000-range and here is some result when thread_num = 1.
```
# benchmark-$name 1 0 2 2 10000 20000 2000 512 160000
rpmalloc     1 threads random exp size [512,160000] 10000 loops 20000 allocs 2000 ops: .... 6769430 memory ops/CPU second (peak 2965MiB)
tcmalloc     1 threads random exp size [512,160000] 10000 loops 20000 allocs 2000 ops: .... 8519908 memory ops/CPU second (peak 333MiB)
jemalloc     1 threads random exp size [512,160000] 10000 loops 20000 allocs 2000 ops: .... 3325522 memory ops/CPU second (peak 384MiB)
```
It seems that the peak memory footprint of rpmalloc is 8x higher than that of jemalloc or tcmalloc in this case. I'm wondering if it is a potential bug or some kind of mis-configuration. I can provide more information if you are interested in this case.

**Comment by mjansson** [comment]
That does look weird, I'll have a look

**Comment by mjansson** [comment]
Could you try the mjansson/cache-tweaks branch and see what results you get?

**Comment by FujiZ** [comment]
Thanks for your reply. I have tested the cache-tweaks branch and the result looks good to me. Here are some results I got:
![image](https://user-images.githubusercontent.com/11678436/128486352-dda33ce4-6513-4400-b926-1a57ec29ff45.png)
![image](https://user-images.githubusercontent.com/11678436/128486720-e693609c-5a5f-4097-8643-ccfc81974803.png)
In the [512, 160000] case, rpmalloc (with cache-tweaks) increase the IOPS and greatly reduces the memory footprint compared to the original one.
And other results shows rpmalloc (with cache-tweaks) has better scalibility compared to other allocators.
![image](https://user-images.githubusercontent.com/11678436/128487905-9ec1fdab-46ae-4e22-b141-9b30cf066d19.png)
![image](https://user-images.githubusercontent.com/11678436/128487920-47ed35d2-1090-44f8-88cd-ed27e9b3ec97.png)
![image](https://user-images.githubusercontent.com/11678436/128487683-acbf8265-448b-44ed-a0d1-d9f8eb3a36a0.png)
![image](https://user-images.githubusercontent.com/11678436/128487696-e1dadb6a-99df-44e5-8caf-c45e4537720e.png)
![image](https://user-images.githubusercontent.com/11678436/128488070-8b214928-b334-4ec9-b575-7c7c1ab29254.png)
![image](https://user-images.githubusercontent.com/11678436/128488092-a7458079-9271-4921-9676-629f059c162d.png)
![image](https://user-images.githubusercontent.com/11678436/128488113-0c9790b8-531d-49f3-b8ff-3ed304d96235.png)
![image](https://user-images.githubusercontent.com/11678436/128488129-e29685fb-7e16-4035-9715-30209ed78794.png)
I think this solved my problem. Thanks!

**Comment by mjansson** [comment]
Great, will merge this, run the test suite and prepare a new release if everything looks good on all platforms.

**Comment by mjansson** [comment]
What do you use to generate those graphs by the way? I was going to run the benchmark suite and update the graphs on the readme, could you share what you use?

**Comment by FujiZ** [comment]
I use matplotlib to generate these figures. You can checkout the script at https://gist.github.com/FujiZ/89387d1a98d763753f2f7c5367a515e2
