### ISSUE TITLE
error C2664: 'void *rpaligned_alloc(size_t,size_t)': cannot convert argument 1 from 'std::align_val_t' to 'size_t'

### ISSUE THREAD

**Issue by XXxR4GALXxx** [mjansson/rpmalloc#261]
rpnew.h - Visual Studio 2022 - C++ / 23.
![image](https://user-images.githubusercontent.com/73304497/143098373-b0590939-18c1-4e3c-9c76-2528f8d3ea64.png)

**Comment by mjansson** [comment]
I added explicit casts now

**Comment by XXxR4GALXxx** [comment]
okie! thx! 👍
