### ISSUE TITLE
MSVC Crash - Debug mode (Visual Studio 2022 / (C++ 23))

### ISSUE THREAD

**Issue by XXxR4GALXxx** [mjansson/rpmalloc#262]
Consider the following code (for example):

```
for (int i = 0; i < 500; ++i)
{
	char* v = (char*)malloc(i+1024);
        if (v)
	    free(v);
}
```

The following Code executes normally. However, when it reaches the end of the program, and the MSVC runtime is executed to terminate the program, it crashes.

![image](https://user-images.githubusercontent.com/73304497/143136059-ae0e2252-dcb9-449a-b138-5f6d2ffab0f6.png)

Call stack:
![image](https://user-images.githubusercontent.com/73304497/143136157-36ad9dd0-31ed-476e-8024-407b955210e4.png)

I'm using Visual studio 2022 - Debug mode, and C++ 20/23 (``/std:c++latest``).

however in release mode, this does not happen.

**Comment by XXxR4GALXxx** [comment]
![image](https://user-images.githubusercontent.com/73304497/143137756-8fc50df4-c259-4992-8447-d4cd4be3a38d.png)
why span_t is null? 🤔

**Comment by mjansson** [comment]
You must pass the sme pointer to free that you got from malloc. You increment the pointer and thus free an invalid pointer.
