### ISSUE TITLE
custom memory_map/memory_unmap need thread-safe or not?

### ISSUE THREAD

**Issue by tufeigunchu** [mjansson/rpmalloc#270]
I can't find any topic on this in the README. I guess it is necessary?

**Comment by mjansson** [comment]
Yes, the functions can be called simultaneously from multiple threads. I'll add a note about it in the docs.

**Comment by mjansson** [comment]
Done in https://github.com/mjansson/rpmalloc/commit/00070f7a3070306cb315934667f57c9569f1fd47
