### ISSUE TITLE
Question about case in _rpmalloc_span_double_link_list_remove

### ISSUE THREAD

**Issue by cipharius** [mjansson/rpmalloc#288]
I was studying the rpmalloc implementation and noticed this piece of code:
https://github.com/mjansson/rpmalloc/blob/2b300ec5cd798e9288e7a61ddeaa8f0c8e92d795/rpmalloc/rpmalloc.c#L1087-L1089

In case of head node removal, it assigns the new head, but it does not update the new head node's prev pointer.
Is this intentional or a bug?

What I would have expected:
```diff
+ span_t* next_span = span->next;
  *head = next_span;
+ if (EXPECTED(next_span != 0))
+     next_span->prev = 0;
```

**Comment by mjansson** [comment]
It is intentional, as the prev pointer is only used for non-head nodes - the new head node does not need a valid prev pointer

**Comment by mjansson** [comment]
As you can see when adding a new node the prev pointer is correctly set on the existing head node

https://github.com/mjansson/rpmalloc/blob/2b300ec5cd798e9288e7a61ddeaa8f0c8e92d795/rpmalloc/rpmalloc.c#L1070

**Comment by cipharius** [comment]
Alright, good to know, thanks!
