### ISSUE TITLE
build failed with msvs 2022

### ISSUE THREAD

**Issue by ktprime** [mjansson/rpmalloc#292]
![image](https://user-images.githubusercontent.com/1461362/198568131-f2103fcc-08d2-48ab-a756-082a9588fa61.png)

![image](https://user-images.githubusercontent.com/1461362/198568302-2f98d644-4e2f-4389-878b-f92b14ac3c4c.png)

 I add malloc.c in my project to build and there are many errors.
so i change some code and it's compiled pass but crash(single thread demo).

![image](https://user-images.githubusercontent.com/1461362/198569059-a9e88605-9391-4319-88c7-85bac3e1f0bb.png)

![image](https://user-images.githubusercontent.com/1461362/198568623-9edae95f-9cd8-4b4c-bbfa-28745b19c799.png)

**Comment by mjansson** [comment]
You should not add `malloc.c` to your project, it is included automatically when needed (determined by the ENABLE_xxx preprocessor directives set). You should only add `rpmalloc.c` to your project.

Make sure to read the "Using" section - https://github.com/mjansson/rpmalloc#using

**Comment by ktprime** [comment]
**If you wish to override the standard library malloc family of functions and have automatic initialization/finalization of process and threads, define ENABLE_OVERRIDE**
if not add malloc.c to my project, how can override  malloc family of functions?

**Comment by mjansson** [comment]
The override is included automatically in the rpmalloc source file (look at the end of the file) if the override preprocessor directives are set - this setup is needed for the interpose functionality on macos for example.

**Comment by ktprime** [comment]
thanks for your reply, it's my issiue
