### ISSUE TITLE
Potential bug: get_thread_id / rpmalloc_heap_thread_set_current

### ISSUE THREAD

**Issue by onelivesleft** [mjansson/rpmalloc#295]
I'm porting rpmalloc to a different language, and ran across this bug (which had me scratching my head for a long time!) - I ran into it because I used the fallback position of `get_thread_id`, namely when it does this:

```
  return (uintptr_t)((void*)get_thread_heap_raw());
```

`rpmalloc_heap_thread_set_current` looks like this:

```
extern inline void rpmalloc_heap_thread_set_current(rpmalloc_heap_t* heap) {
	heap_t* prev_heap = get_thread_heap_raw();
	if (prev_heap != heap) {
		set_thread_heap(heap);
		if (prev_heap)
			rpmalloc_heap_release(prev_heap);
	}
}
```

The issue being that the thread id changes after the call to `set_thread_heap`, at which point `prev_heap.owner_thread` becomes incorrect (and if freed will fire the assert that checks it).

This only ever triggered in the threadspam test, and because its the last resort returned by `get_thread_id` this will be a very rare bug; I'm not surprised no-one has reported it.

**Comment by mjansson** [comment]
I would assume not many people have tried using it on a platform that falls back to that `get_thread_id` implementation. I'll see if I can sort out the implementation to do the right thing in this fallback case.

I would suggest you implement a correct `get_thread_id` in your port though, this fallback was never indented for actual use :)

**Comment by onelivesleft** [comment]
`I would suggest you implement a correct get_thread_id in your port though, this fallback was never indented for actual use :)`

Yeah, was an easy fix as there's a built-in `thread_index` I could use.

**Comment by onelivesleft** [comment]
OT, but I don't want to make an issue because it's probably not a bug: why is this line a naked `assert` rather than `rpmalloc_assert`?

https://github.com/mjansson/rpmalloc/blob/develop/rpmalloc/rpmalloc.c#L1546

**Comment by mjansson** [comment]
I guess I simply forgot to update that line when introducing the error callback and custom assert macro :)

**Comment by mjansson** [comment]
Fixed now

**Comment by mjansson** [comment]
I decided to simply error out in compilation when there's no implementation for get_thread_id as there are assumptions in the implementation that the thread ID is static for the lifetime of the thread.

**Comment by onelivesleft** [comment]
Seems like the best solution.  Can I ask on my way out the door: what does the `rp_` stand for?

**Comment by mjansson** [comment]
I used to run my own small company called "Rampant Pixels" - but it doesn't exist anymore, so these days it could mean anything :)

**Comment by onelivesleft** [comment]
Hey, spotted another thing that looks weird, but not sure is really a bug (so just posting here instead of raising): 

https://github.com/mjansson/rpmalloc/blob/668a7f81b588a985c6528b70674dbcc005d9cb75/rpmalloc/rpmalloc.c#L1871

atomic_incr returns the new value, so is the `1 + ...` needed?

**Comment by mjansson** [comment]
No, it is not needed - I think it's a left over from the initial iterations where the atomic wrappers had the same semantics as atomic_fetch_add and returned the original value instead of matching InterlockedIncrement semantics returning the incremented value.

It's not really a bug, it only affects the starting heap ID value which will be set to 2 instead of 1 - the important bit is that it's non-zero.
