### ISSUE TITLE
Segmentation fault when revising parameters(span_size and span_map_count)

### ISSUE THREAD

**Issue by AaronZhao99** [mjansson/rpmalloc#299]
Hi, when I benchmarking , revising parameters(span_size and span_map_count), and executing the sh script test in the repo, the error came up

**rpmalloc.c**
_#define DEFAULT_SPAN_MAP_COUNT    16_
#define _memory_default_span_size (16 * 1024)_
_#define _memory_default_span_size_shift 14__

<img width="483" alt="image" src="https://user-images.githubusercontent.com/71221586/218403553-99d67876-a049-4f01-aadc-45eeca8521f2.png">
Hope you can take a look，thanks!

**Comment by mjansson** [comment]
There was an incompatibility with the handling of boundary between medium and large sized blocks when the span size was reconfigured. This has now been fixed, please test the latest develop branch again.
