### ISSUE TITLE
Linking error: unresolved external symbol _rpmalloc_module_init

### ISSUE THREAD

**Issue by rjobling** [mjansson/rpmalloc#305]
I'm trying to make use of rpmalloc in a relatively large windows code base. 

I'm getting this error: unresolved external symbol _rpmalloc_module_init

What does this signify? I can see this code in the malloc.c

```
#pragma section(".CRT$XIB",read)
__declspec(allocate(".CRT$XIB")) void (*_rpmalloc_module_init)(void) = _global_rpmalloc_init;
#pragma comment(linker, "/include:_rpmalloc_module_init")
```

But I'm not sure what this is doing.

In terms of options I have ENABLE_PRELOAD=1

My hope was that I could fairly easily replace our existing allocator with the preload option automatically handling initialization for our process and threads. The documentation seems to suggest this is possible but maybe that's not the case.

**Comment by rjobling** [comment]
Not sure what the purpose of #pragma comment(linker, "/include:_rpmalloc_module_init") is but I've commented that out and things seem to be working fine after a few patches to fix warnings about some unused functions.

**Comment by mjansson** [comment]
The #pragma section is to make sure that the global init is called before any global constructors are called - C++ in particular has a nasty habit of doing memory allocation during global variable construction.

The #pragma comment is to force the linker to include the module init symbol and not treat it as unused.

Unfortunately overriding global allocation on Windows for C style allocation (malloc/free) is very hard as it requires rewiring the executable in runtime. C++ new/delete works pretty well.

**Comment by mjansson** [comment]
I can't seem to reproduce this, closing for now - let me know if you still need assistance in sorting this out.

**Comment by Wodann** [comment]
This happened to me on Windows i686 MSVC (see [CI logs](https://github.com/NomicFoundation/hardhat/actions/runs/8519767056/job/23334476230?pr=4943#step:13:47))

**Comment by Wodann** [comment]
This PR resolves the issue: https://github.com/mjansson/rpmalloc/pull/331

**Comment by cvet** [comment]
This compilation error happened for me when compiling to x86 architecture.

**Comment by cvet** [comment]
Adding _ to beginning of symbol solve the problem.
#pragma comment(linker, "/include:__rpmalloc_module_init")
So problem in symbols mangling under different platforms.
Need to separate x86/amd64 pragma for correct linkage.
