### ISSUE TITLE
`SIGABRT` when building w/ `-DENABLE_ASSERTS=1 -DENABLE_OVERRIDE=1 -DENABLE_PRELOAD=1`

### ISSUE THREAD

**Issue by therealthingy** [mjansson/rpmalloc#307]
* Test program:
  ```C
  // Basically a program which does do nothing (I.E., there can't be memory leaks caused by the program itself ...)
  #include <rpmalloc.h>

  int main(int argc, char** argv) {
    rpmalloc_linker_reference();

    return 0;
  }
  ```

* Result (on Ubuntu 22.04 LTS) when compiled w/ `-DENABLE_ASSERTS=1 -DENABLE_OVERRIDE=1 -DENABLE_PRELOAD=1`:
  ```bash
  ❯ ./test/__testing
  __testing: /home/user/repos/mem-alloc/alloc/protos/rpmalloc/src/rpmalloc.c:1420: _rpmalloc_span_finalize: Assertion `(span->list_size == span->used_count) && "Memory leak detected"' failed.
  [1]    8570 IOT instruction  ./test/__testing
  ```

* Result when compiled w/ `-DENABLE_ASSERTS=1 -DENABLE_OVERRIDE=0 -DENABLE_PRELOAD=0`:
  ```bash
  ❯ ./test/__testing
  # (No crash ...)
  ```

The "supposed" memory leak is thus most likely caused by the OS loader itself (and not the program).

Suggestion: Add 
  ```C
  #if !ENABLE_OVERRIDE
    assert(MEMORY LEAK CHECK);
  #endif
  ```
to all memory leak asserts.

**Comment by mjansson** [comment]
Is this still an issue with the latest develop branch? Closing this for now, reopen if you want to dig further into it if it is still happening.
