### ISSUE TITLE
Segmentation fault with the rewrite branch in certain benchmarks

### ISSUE THREAD

**Issue by KTSnowy** [mjansson/rpmalloc#313]
The newer rewrite branch seems to be crashing with a segmentation fault in some benchmarks.

I tried running the benchmarks from: https://github.com/daanx/mimalloc-bench, with the code in the newer branch. The ghostscript, lua and rocksdb benchmarks crash with a segmentation fault, and the redis benchmark results in an infinite loop.

**Comment by KTSnowy** [comment]
I have noticed another anomaly in the rewrite code, from the mimalloc-bench code it seems that page reclaims for rpmalloc are extremely high in certain benchmarks.

```
# test    alloc   time  rss    user  sys   page-faults page-reclaims
sh8benchN   rp    22.19 181544 13.58 11.70 0           2466417
sh8benchN   rp    21.27 190632 13.17 11.08 0           2466019
sh8benchN   rp    20.61 179172 12.82 10.56 0           2466126
sh8benchN   rp    20.75 183456 12.60 10.84 0           2466496
sh8benchN   rp    21.41 184020 13.31 10.99 0           2466958
```

Around 2.5 million page reclaims for this benchmark, with the system malloc having around 150k, and mimalloc only having around 15k.

```
# test        alloc   time   rss   user sys  page-faults page-reclaims
xmalloc-testN   rp    12.238 45336 2.85 3.11 0           591105
xmalloc-testN   rp    12.103 44136 2.95 3.04 0           596727
xmalloc-testN   rp    10.555 45300 3.28 3.26 0           685687
xmalloc-testN   rp    11.020 44308 3.22 3.23 0           657453
xmalloc-testN   rp    12.245 45848 2.89 3.08 0           587162
```

It's also quite high in the xmalloc-test benchmark at around 600k, with the system malloc having around 50k, and mimalloc only having around 2k.

I'll also include the Redis benchmark errors here, this results in the benchmarks getting stuck (on GitHub Actions) and not being able to progress to the next ones.

It might be safe to assume that the server is immediately crashing with a segmentation fault as well, if this is the same issue as the other ones:

```
run 1: redis rp: LD_PRELOAD=/home/runner/work/mbench/mbench/extern/rp/bin/linux/release/x86-64/librpmallocwrap.so /home/runner/work/mbench/mbench/extern/redis-7.0.12/src/redis-benchmark -r 1000000 -n 100000 -q -P 16 lpush a 1 2 3 4 5 lrange a 1 5
start server
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
WARNING: Could not fetch server CONFIG
```

The others I mentioned crash with signal 11 (segmentation fault):

```
run 1: gs rp: LD_PRELOAD=/home/runner/work/mbench/mbench/extern/rp/bin/linux/release/x86-64/librpmallocwrap.so gs -dBATCH -dNODISPLAY /home/runner/work/mbench/mbench/extern/large.pdf
Command terminated by signal 11
gs          rp    0:01.99 76720 1.79 0.06 0 2222
```

```
run 1: lua rp: LD_PRELOAD=/home/runner/work/mbench/mbench/extern/rp/bin/linux/release/x86-64/librpmallocwrap.so make
~/work/mbench/mbench/extern/lua ~/work/mbench/mbench/extern/lua ~/work/mbench/mbench/out/bench
rm -f liblua.a lua lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o ltests.o lua.o lauxlib.o lbaselib.o ldblib.o liolib.o lmathlib.o loslib.o ltablib.o lstrlib.o lutf8lib.o loadlib.o lcorolib.o linit.o
~/work/mbench/mbench/extern/lua ~/work/mbench/mbench/out/bench
Command terminated by signal 11
lua         rp    0:00.15 10840 0.00 0.00 0 224
```

```
run 1: rocksdb rp: LD_PRELOAD=/home/runner/work/mbench/mbench/extern/rp/bin/linux/release/x86-64/librpmallocwrap.so /home/runner/work/mbench/mbench/extern/rocksdb-8.1.1/db_bench --benchmarks=fillrandom
... finished 1000000 ops                              
RocksDB:    version 8.1.1
Date:       Thu Jul 27 05:34:08 2023
CPU:        2 * Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
CPUCache:   36608 KB
... finished 100 ops                              
[REDACTED]                            
... finished 1000000 ops                              
Received signal 11 (Segmentation fault)
Invoking GDB for stack trace...
GDB failed; falling back on backtrace+addr2line...
#0   /home/runner/work/mbench/mbench/extern/rp/bin/linux/release/x86-64/librpmallocwrap.so(__libc_free+0xea) [0x7f5a5f13a36a] ??	??:0	
Command terminated by signal 11
rocksdb     rp    0:07.36 131096 5.89 1.82 2 2358
```

This line caught my attention:

```
#0   [redacted]/librpmallocwrap.so(__libc_free+0xea) [0x7f5a5f13a36a] ??	??:0	
Command terminated by signal 11
```
If I understand correctly how the override is meant to work, then `__libc_free+0xea` shouldn't be there right? Unless I'm mistaken, this means that there's a call to glibc free somewhere in there when it shouldn't.

@mjansson, the rocksdb benchmark seems to be the most descriptive when it comes to the error, would it be safe to assume that the segmentation fault in the rocksdb benchmark is the same as the other 3?

**Comment by mjansson** [comment]
It seems the gs test does some free in global destructors which is called after the rpmalloc global destructor. Will fix that so it is supported.

Regarding page reclaims the current rewrite branch is extremely easger to decommit any unused memory pages. Working on some good heuristics on when to keep pages around and when to decommit.

**Comment by mjansson** [comment]
I've pushed a couple of fixes, if you want to try them out that would be great.

If you want to run without the aggressive decommit/recommit pages you can change the ENABLE_DECOMMIT define to 0

**Comment by mjansson** [comment]
The ENABLE_DECOMMIT=1 should work pretty well now in all the benchmarks

**Comment by mjansson** [comment]
Closing for now, let me know if there are more issues
