### ISSUE TITLE
Improve cross thread use cases

### ISSUE THREAD

**Issue by mjansson** [mjansson/rpmalloc#63]
Improve cross thread use cases, either by redesigning the deferred deallocation scheme or introducing an optional opportunistic locking scheme for freeing blocks in other heaps.

**Comment by MJansson** [comment]
Core use case is garbage collection in separate thread(s)

**Comment by NickStrupat** [comment]
Would this enable the following scenario...?

- 4 threads
- each thread has a thread-local heap
- all threads share a single global heap
  - the distinction being that global locking is required
- a heap for 2 threads which wish to share only with each other the distinction
  - the distinction being that global locking is not required, only locking between the 2 threads sharing the given heap

**Comment by waddlesplash** [comment]
Another usecase related to this: See https://review.haiku-os.org/c/haiku/+/790#message-ff4bcefd_c98ad80a and then the 2 other comments by the same author immediately following that one.

We "solved" this for the time being by reducing the thread cache default from 16 to 4, and the global cache from 64 to 32, but as Haiku is in some ways "pervasively multithreaded", some better heuristics internally would be nice, too.

**Comment by mjansson** [comment]
Alright, I can see how the deferred deallocation scheme would be a massive problem in this case :) I'll look into this

**Comment by mjansson** [comment]
Reading through the comments again and doing some simple tests simulating it I think the best solution to this problem is adding a simple dynamic logic to the cache size based on the number of allocations of the given size class.

I'll draw up a proposed implementation in a branch that you can try out.

**Comment by mjansson** [comment]
@waddlesplash could you try the installer with a restored thread cache multiplier but using the mjansson/adaptive-thread-span-cache branch? It has a simple adaptive cache size based on the amount of allocations done by the thread which should improve your use case.

**Comment by waddlesplash** [comment]
Without patch, default cache multipliers: memory usage peaks at around 227MB.
Without patch, our reduced cache multipliers: memory usage peaks at 37MB.
With patch, default cache multipliers: memory usage peaks at 18MB (!!).

So yes, it seems that helps quite a lot 😄

**Comment by mjansson** [comment]
Great, I'll try to improve the logic a bit and also handle the heap re-use after thread termination, then get it merged to develop branch

**Comment by mjansson** [comment]
Did some additional improvements to the thread cache size limit heuristics, please try again. If it looks good, I'll merge #96

**Comment by mjansson** [comment]
I did tests and benchmarks here and it looks good, merged to develop branch now

**Comment by mjansson** [comment]
Cross thread deallocations have been greatly improved with the introduction of per-size-class deferred free lists
