### ISSUE TITLE
GCD and rpmalloc_thread_initialize

### ISSUE THREAD

**Issue by vitorhugomagalhaes** [mjansson/rpmalloc#73]
Hi,

I'm trying to include rpmalloc into my ios project however, since we use GCD I'm not sure where to call rpmalloc_thread_initialize.

Without this call the app crashes in all the callers that are not performed in the main thread where rpmalloc_initialize was called.

Thanksm

**Comment by MJansson** [comment]
Are you using the malloc wrappers in malloc.c? The idea is that the pthread create calls should be intercepted and threads automagically initialized.

**Comment by vitorhugomagalhaes** [comment]
I tried the malloc wrappers and the code crashes. I'm not sure that intercepting the pthread_create actually solves the issue when using GCD. Are you sure GCD threads are created with pthread library ?

**Comment by victorstewart** [comment]
hey I also was really interested in using rpmalloc in my iOS app (Objective C++), but I also use GCD to dispatch work at will... thus can't. I use a lot of static queues to synchronize memory access... but all object creation happens on random queues aka `dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)`

**Comment by dcouture2** [comment]
You could try it out with this branch

https://github.com/dcou/rpmalloc-greedy/tree/greedy_unmap

**Comment by victorstewart** [comment]
@dcouture2 what’s the difference? i don’t see it in the readme

**Comment by MJansson** [comment]
Related #63

**Comment by MJansson** [comment]
Any chance you could provide a minimal reproduction of this issue?

**Comment by mjansson** [comment]
Ping @vitorhugomagalhaes and @victorstewart on providing more info or a reproduction case

**Comment by mjansson** [comment]
This should work now in latest develop branch if ENABLE_PRELOAD is set to 1 (in which case each thread will self-init when needed)
