### ISSUE TITLE
Very high memory usage under shbench

### ISSUE THREAD

**Issue by waddlesplash** [mjansson/rpmalloc#74]
As seen here: https://github.com/ezrosent/allocators-rs/blob/master/info/elfmalloc-performance.md#shbench

> Also of note is the memory consumption of ptmalloc2, llalloc and rpmalloc: something about the varying lifetimes of objects seems to trip these allocators up here, as they use over an order of magnitude more memory than jemalloc and elfmalloc.

Indeed, it looks like rpmalloc is using over 1GB of memory, vs. < 50MB for `jemalloc` and friends.

Other than that, these benchmarks seem to show rpmalloc having a *very* good performance/overhead tradeoff. Nice!

**Comment by MJansson** [comment]
Interesting, will look into the excessive memory usage and also at potential improvements that could be found using those benchmarks.

**Comment by mjansson** [comment]
The link does not provide detailed information on how memory usage is measured. I did some checks with the shbench tool linked on that page (from https://github.com/cksystemsgroup/scalloc-artifact) and I was unable to see any massive memory use with rpmalloc (while providing the measures speedups over the system allocator)

For example, allocating blocks [8-4000] bytes. System allocator:

```Total elapsed time for 3 threads: 6.00 (6.2831 CPU)
rdtsc time: 8.169703
Command exited with non-zero status 32
        Command being timed: "out/Release/shbench"
        Maximum resident set size (kbytes): 237736
        Minor (reclaiming a frame) page faults: 59112
        Voluntary context switches: 366
        Involuntary context switches: 1674
```

And using LD_PRELOAD rpmalloc:

```Total elapsed time for 3 threads: 3.00 (3.2940 CPU)
rdtsc time: 4.283471
        Maximum resident set size (kbytes): 238740
        Minor (reclaiming a frame) page faults: 59110
        Voluntary context switches: 15
        Involuntary context switches: 851
```

**Comment by waddlesplash** [comment]
Hmm, it doesn't list what block size they used, either. Maybe they were using a much larger one?

The person who did those benchmarks (ezrosent) seems MIA, so I don't think we'll be able to ask them exactly what they did... I guess closing this as "unreproducible" is fine then.

**Comment by mjansson** [comment]
It mentioned "medium size" being a few kilobytes so I tried finding some combo of parameters showing this excessive memory use but could not. I'll do some more tinkering using that shbench tool though.

**Comment by mjansson** [comment]
Mitigated by adaptive thread cache in #96
