### ISSUE TITLE
Support 1GiB huge pages

### ISSUE THREAD

**Issue by mjansson** [mjansson/rpmalloc#94]

**Comment by aganea** [comment]
What is the impediment for supporting 1GB pages? Could you please quickly explain?

**Comment by mjansson** [comment]
With the changes done for the 1.4 release it should be possible, I'll have a look as soon as I can.

**Comment by mjansson** [comment]
I've verified with works with up to 4GiB huge pages with #118 now on develop branch

**Comment by aganea** [comment]
Thanks, it works! However I meant to conduct a test where only 1 GB pages would be used, and when I force 1 GB pages, it seems the app. using rpmalloc is using more memory than it should. I've ensured `config->enable_huge_pages` is set, and added `large_page_minimum = 1ULL << 30;` at rpmalloc.c L1779 (on develop branch). I'm not sure it's the right way to achieve that, would you possibly have anything else to suggest?

**Comment by aganea** [comment]
Actually you can see that effect with 2 MB pages as well (I'm on Windows 10 btw). Just force `large_page_minimum = 1ULL << 21;` and you can see the private bytes of the application going way above what it should.

**Comment by mjansson** [comment]
Will take a look at that, perhaps the tuning of span preallocation needs modifications for huge pages.

**Comment by mjansson** [comment]
Oh, I just realized that each heap does a hard mapping of a memory page, so if pages are 1GiB that's gonna be a lot of waste. Will fix this.

I'm not seeing any huge increase in memory usage with 2MiB pages (but perhaps you have a large number of threads, and thus heaps, in your tests? Then one-page-per-heap would impact usage)

**Comment by mjansson** [comment]
@aganea could you try the mjansson/huge-pages-heap-share branch and see if you get better memory usage patterns when using huge pages?

**Comment by mjansson** [comment]
I ran benchmark suite with these improvements and everything looks good, merged
